### ISSUE TITLE
GET movie By Id

### ISSUE THREAD

**Issue by Flooooooooooorian** [neuefische/ffm-java-23-1-team-project-1#14]
**As a User** 
**I need** to search for ... in my library
**to be able to** quickly find a specific ...

#### Description
Implement a search feature that allows users to search for movie based on criteria such as title, author, or genre.

#### Acceptance Criteria

- [x] Create a GET "/api/movies/{id}" endpoint to fetch the movie specified by the id.
- [x] Display all informations given from the backend on a extra Route for each movie "/movies/:id
- [x] When clicking a movie in the list view or navigating directly via the url the details page should be shown

#### Tasks

- [x] Implement a component that shows the movie Details when you click on movie in the list view
- [x] Create a GET request to retrieve the movie data from the backend (Get By Id).
- [x] Implement Unit and Integration Test.
- [x] add some styling
