### ISSUE TITLE
Edit (PATCH) movie to favourites

### ISSUE THREAD

**Issue by UlrikeWerner** [neuefische/ffm-java-23-1-team-project-1#20]
**As a User**
**I need** to add a movie to my favourites

#### Description
Implement a feature that allows users to add the movie in their library. 

#### Acceptance Criteria

- [ ] A "heart"-Button is displayed on the details-page for each-movie.
- [ ] When the "heart" button for a movie is clicked, the movie will be displayed in the favourites list
- [ ] Create an PUT Endpoint "/api/movies/{id} to update the movie.

#### Tasks

- [ ] Add an "heart" button for each movie in the UI.
- [ ] Implement an edit form to modify movie details.
- [ ] Create a PUT request to update movie details on the backend.
- [ ] Display updated information in the frontend after saving changes.
- [ ] Implement Unit and Integration Test.
