### ISSUE TITLE
DELETE movie from the DB

### ISSUE THREAD

**Issue by LTschapalda** [neuefische/ffm-java-23-1-team-project-1#24]
**As a User**
**I need** to delete a movie from my favourites library

#### Description
Implement a feature that allows users to delete a movie from their library. Users should be able to remove a book they no longer wish to keep in their collection.

#### Acceptance Criteria

- [x] Create a DELETE Endpoint "/api/movies/{id}" which deletes the movie specified by the id.
- [x] On the Details-Page of each movie should be a "delete" Button.
- [x] When clicking on the "Delete" button, the movie should be removed from the database.

#### Tasks

- [x] Add a "Delete" button for each movie in the UI.
- [x] Create a DELETE request or endpoint to remove the movie from the backend.
- [x] Implement Unit and Integration Test.
