### ISSUE TITLE
Add (POST) movie

### ISSUE THREAD

**Issue by Flooooooooooorian** [neuefische/ffm-java-23-1-team-project-1#31]
**As a User** 
**I need to** add a new movie to my library
**to be able to** keep track of new movie I acquire

## Description
Implement a feature that allows users to add a new movie to their library. Users should be able to enter movie details such as (title, author, genre, and publication date).

## Acceptance Criteria

- [ ] Create a POST endpoint "/api/movies" to add a new movie to the backend.
- [ ] The the Route "/movies/add" should display the form, for the user to add a movie.
- [ ] Ensure that the added movie appears in the list of movies.

## Tasks

(for developers team)

- [ ] Create a "Add movie" button in the UI.
- [ ] Implement a form to input movie details.
- [ ] Create a POST request to send movie data to the backend.
- [ ] Implement Unit and Integration Test.
- [ ] add some styling 

```[tasklist]
### Tasks
```
